version: '2'
services:
  reactive-spring-boot:
    image: 'vitryssen/reactive-spring-boot:latest'
    ports:
      - '8080:8080'
      - '5001:5000'
    environment:
      SERVER_PORT: '8080'
      SPRING.DATASOURCE.URL: r2dbc:postgresql://postgres:5432/postgres
      SPRING.DATASOURCE.USERNAME: "postgres"
  postgres:
    image: postgres
    user: postgres
    ports:
      - '5433:5432'
    volumes: 
          - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
        POSTGRES_DB: "postgres"