version: '3.3'
services:
  postgres:
    image: 'postgres:14.1'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - app_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fruits
  quarkus:
    image: 'sha256:fd89c483400f7266b1a90f971a915056d1c83662d4048aabb76eb96e73217ef4' #Change to your local quarkus instance
    ports:
      - '8080:8080'
    networks:
      - app_net
    environment:
      quarkus.datasource.reactive.url: 'postgresql://postgres:5432/fruits'
networks:
  app_net:
    driver: bridge
