version: '3.9'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    networks:
      - app_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fruits
  quarkus:
    image: 'nilkas/quarkus-mutiny:latest'
    environment:
      quarkus.datasource.reactive.url: 'postgresql://postgres:5432/fruits'
      quarkus.datasource.username: 'postgres'
      quarkus.datasource.password: 'postgres'
    ports:
      - '8080:8080'
    networks:
      - app_net
networks:
  app_net:
    driver: bridge