version: '2'
services:
  imperative-spring-boot:
    image: vitryssen/imperative-spring-boot
    ports:
      - '8081:8081'
      - '5000:5000'
    environment:
      SERVER_PORT: '8081'
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/postgres
      SPRING.DATASOURCE.USERNAME: "postgres"
    scale: 1
  postgres:
    image: postgres
    user: postgres
    volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5432:5432'
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
        POSTGRES_DB: "postgres"